### ISSUE TITLE
Error on secretscope delete/update

### ISSUE THREAD

**Issue by rahdjoudj** [microsoft/azure-databricks-operator#64]
Hi,

I've been trying to delete and update secretScope and run into issue.
first update:
Rbac is missing some permission to patch the existing
```
'events "***" is forbidden: User "system:serviceaccount:azure-databricks-operator-system:default" cannot patch resource "events" in API group "" in the namespace "****"' (will not retry!)
```

Second delete:
Cascade of events after a ```kubectl delete secretscope```
it goes in a CrashLoop at the operator pod level.
only a delete of the pod will bring it back (plus some manual cleanup)
To get rid of the secretscope in kube I have to delete the finalizer 
```
2019-10-01T01:07:41.687Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "secretscope", "request": "***/*********", "error": "error when submitting secret scope to the API: Response from server (400) {\"error_code\":\"RESOURCE_ALREADY_EXISTS\",\"message\":\"Scope ***** already exists!\"}"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
```

```
2019-10-01T01:07:42.687Z	INFO	controllers.SecretScope	Finish reconcile loop for dx/lbr-alarm-95986
E1001 01:07:42.687910       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:76
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:65
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/workspace/controllers/secretscope_controller_databricks.go:193
/workspace/controllers/secretscope_controller_finalizer.go:37
/workspace/controllers/secretscope_controller.go:66
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:216
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:192
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:171
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1155031]

goroutine 320 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x12cf380, 0x215a8a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/microsoft/azure-databricks-operator/controllers.(*SecretScopeReconciler).delete(0xc000222240, 0xc006ba5680, 0x1, 0x1470e27)
	/workspace/controllers/secretscope_controller_databricks.go:193 +0x41
github.com/microsoft/azure-databricks-operator/controllers.(*SecretScopeReconciler).handleFinalizer(0xc000222240, 0xc006ba5680, 0xc00041a120, 0xc00626b170)
	/workspace/controllers/secretscope_controller_finalizer.go:37 +0x95
github.com/microsoft/azure-databricks-operator/controllers.(*SecretScopeReconciler).Reconcile(0xc000222240, 0xc00349455a, 0x2, 0xc003494540, 0xf, 0x216e900, 0x0, 0x0, 0x0)
	/workspace/controllers/secretscope_controller.go:66 +0x7af
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000206000, 0x131a4e0, 0xc004bbca40, 0x131a400)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:216 +0x149
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000206000, 0xc000add300)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:192 +0xb5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000206000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005e90a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005e90a0, 0x3b9aca00, 0x0, 0xc000000001, 0xc0004ae9c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005e90a0, 0x3b9aca00, 0xc0004ae9c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:157 +0x311
```

**Comment by Azadehkhojandi** [comment]
related issue #94
